/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Castillo.Util;
import beu.Curso;
import beu.Estudiante;
import bll.GestionCursos;
import bll.GestionEstudiante;
import bll.GestionMatricula;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author labctr
 */
public class frmRegistroMatricula extends javax.swing.JInternalFrame {

    private final String titulo = "Registro de Matrícula";
    //Servicio //Bussines Logic Layer
    private GestionCursos cursosBll = new GestionCursos();
    private GestionEstudiante estudiantesBll = new GestionEstudiante();
    private GestionMatricula matriculasBll = new GestionMatricula();
    private List<Curso> cursos;
    private List<Estudiante> estudiantes;

    private boolean validar() {
        Curso cr = (Curso) this.cmbCursos.getSelectedItem();
        Estudiante est = (Estudiante) this.cmbEstudiantes.getSelectedItem();
        if (est.getNombre().equals("--Seleccione--")) {
            vtnPrincipal.verMensaje("Estudiante no Válido", JOptionPane.WARNING_MESSAGE, titulo);
            return false;
        }
        if (cr.getTitulo().equals("--Seleccione--")) {
            vtnPrincipal.verMensaje("Curso no Válido", JOptionPane.WARNING_MESSAGE, titulo);
            return false;
        }
        return true;

    }

    private void crearMatricula() throws IOException {
        Curso cr = (Curso) this.cmbCursos.getSelectedItem();
        Estudiante est = (Estudiante) this.cmbEstudiantes.getSelectedItem();
        matriculasBll.crear();
        matriculasBll.configurar(cr, est);
        matriculasBll.archivar();
    }

    private void leerCursos() {
        try {
            Curso ficticio = new Curso("--Seleccione--", "", 0.0f);
            this.cmbCursos.addItem(ficticio);
            cursos = cursosBll.getCursos();
            //Este código es una expresión lambda
            cursos.forEach((c) -> {
                this.cmbCursos.addItem(c);
            });

        } catch (Exception e) {
            Util.imprimir("Error:¡!" + e.toString());
            vtnPrincipal.verMensaje("Error al leer los Cursos ", JOptionPane.ERROR_MESSAGE, titulo);
        }
    }

    private void leerEstudiantes() {
        try {
            Estudiante ficticio = new Estudiante();
            ficticio.setNombre("--Seleccione--");
            ficticio.setApellido("");
            this.cmbEstudiantes.addItem(ficticio);
            estudiantes = estudiantesBll.leerEstudiantes();

            //Este código es una expresión lambda
            estudiantes.forEach((c) -> {
                this.cmbEstudiantes.addItem(c);
            });

        } catch (Exception e) {
            Util.imprimir("Error:¡!" + e.toString());
            vtnPrincipal.verMensaje("Error al leer los Estudiantes ", JOptionPane.ERROR_MESSAGE, titulo);
        }
    }

    /**
     * Creates new form RegistroMatricula
     */
    public frmRegistroMatricula() {
        initComponents();
        leerCursos();
        leerEstudiantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistro = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        cmbCursos = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        cmbEstudiantes = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblRegistro.setFont(new java.awt.Font("Century Schoolbook L", 1, 22)); // NOI18N
        lblRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistro.setText("Registro de Matrícula");

        lblEstudiante.setFont(new java.awt.Font("Century Schoolbook L", 0, 15)); // NOI18N
        lblEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstudiante.setText("Estudiante:");

        lblCurso.setFont(new java.awt.Font("Century Schoolbook L", 0, 15)); // NOI18N
        lblCurso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCurso.setText("Curso:");

        cmbCursos.setFont(new java.awt.Font("STIX Math", 2, 15)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Century Schoolbook L", 1, 15)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon("/home/labctr/NetBeansProjects/Mishell/Ejercicio03U3 (1)/save.png")); // NOI18N
        btnGuardar.setText("    Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cmbEstudiantes.setFont(new java.awt.Font("STIX Math", 2, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEstudiantes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if(this.validar()){
                this.crearMatricula();
                vtnPrincipal.verMensaje("Matrícula registrada Correctamente ", JOptionPane.INFORMATION_MESSAGE, titulo);
            }

        } catch (Exception e) {
            Util.imprimir("Error:¡!" + e.toString());
            vtnPrincipal.verMensaje("Error al Crear la Matrícula ", JOptionPane.ERROR_MESSAGE, titulo);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Curso> cmbCursos;
    private javax.swing.JComboBox<Estudiante> cmbEstudiantes;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblRegistro;
    // End of variables declaration//GEN-END:variables
}
