/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Castillo.Util;
import beu.Curso;
import beu.Matricula;
import bll.GestionCursos;
import bll.GestionMatricula;
import java.io.IOException;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mishell
 */
public class frmReporteCalificaciones extends javax.swing.JInternalFrame {

    private final String titulo = "Reporte de Calificaciones";
    private GestionCursos cursoBll = new GestionCursos();
    private GestionMatricula matriculaBll = new GestionMatricula();
    private List<Curso> cursos;
    private List<Matricula> calificaciones;
    private final DefaultTableModel dtmCalificaciones = new DefaultTableModel();

    private void leerCurso() {
        try {
            Curso ficticio = new Curso("--Seleccione--", "", 0.0f);
            this.cmbCurso.addItem(ficticio);
            cursos = cursoBll.getCursos();;
            //Exprecion lambda
            cursos.forEach((c) -> {
                this.cmbCurso.addItem(c);
            });
        } catch (Exception e) {
            Util.imprimir("Error: " + e.toString() + "\n");
            vtnPrincipal.verMensaje("Error al leer cursos", JOptionPane.ERROR_MESSAGE, titulo);
        }
    }

    private void configurarModeloTabla() {
        String[] columnas = {"Nombre", "Promedio", "Estado"};
        this.dtmCalificaciones.setColumnIdentifiers(columnas);
        this.tblCalificaciones.setModel(dtmCalificaciones);
    }

    private void mostrarCalificaciones() {
        int lim = this.dtmCalificaciones.getRowCount() - 1;
        for (int i = lim; i >= 0; i--) {
            this.dtmCalificaciones.removeRow(i);
        }
        for (Matricula m : calificaciones) {
            Vector fila = new Vector();
            fila.addElement(m.getEstudiante());
            fila.addElement(m.getPromedio());
            fila.addElement(m.getEstado());
            this.dtmCalificaciones.addRow(fila);
        }
        this.tblCalificaciones.setModel(dtmCalificaciones);
    }

    private void buscarMatriculas() throws IOException {
        Curso seleccionado = (Curso) this.cmbCurso.getSelectedItem();
        calificaciones = matriculaBll.reportar(seleccionado.getTitulo());
        mostrarCalificaciones();
    }

    /**
     * Creates new form frmReporteCalificaciones
     */
    public frmReporteCalificaciones() {
        initComponents();
        this.leerCurso();
        this.configurarModeloTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCalificaciones = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte de Calificaciones");

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 3, 15)); // NOI18N
        jLabel1.setText("Curso:");

        cmbCurso.setFont(new java.awt.Font("STIX", 1, 15)); // NOI18N

        tblCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCalificaciones);

        btnBuscar.setIcon(new javax.swing.ImageIcon("/home/labctr/NetBeansProjects/Mishell/Ejercicio03U3 (1)/Navi.png")); // NOI18N
        btnBuscar.setToolTipText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            this.buscarMatriculas();
            vtnPrincipal.verMensaje("Busqueda correcta ", JOptionPane.INFORMATION_MESSAGE, titulo);
        } catch (Exception e) {
            Util.imprimir("\nError" + e.toString() + "\n");
            vtnPrincipal.verMensaje("Error al buscar Matrícula ", JOptionPane.ERROR_MESSAGE, titulo);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<Curso> cmbCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCalificaciones;
    // End of variables declaration//GEN-END:variables
}
